name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
