name: Lint and validate Helm chart
on:
  pull_request:
    types:
      - opened
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Setup helm 
        uses: azure/setup-helm@v3
        with:
           version: 'v3.10.0' 
        id: install
       
      - name: Test helm
        run: helm version
