name: Build and Push Image
on:
  push:
    branches:
      - main

jobs:
  versioning:
    name: Check and manage versioning
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.bump-version.outputs.new_tag || steps.bump-version.outputs.previous_tag }}
      
    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.1
      id: bump-version
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        default_bump: false    
        
  build_image:
    needs: versioning
    name: Build and push container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Image - x86_64
        id: build-image-x86_64
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-app
          tags: ${{ needs.versioning.outputs.release_tag }}
          containerfiles: |
            ./Dockerfile

      - name: Build Image - ARM64
        id: build-image-arm64
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-app
          tags: ${{ needs.versioning.outputs.release_tag }}-arm64
          containerfiles: |
            ./Dockerfile-arm64
          
      - name: Push To quay.io
        id: push-x86
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image-x86_64.outputs.image }}
          tags: ${{ needs.versioning.outputs.release_tag }}
          registry: quay.io/kubealex
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          
      - name: Push To quay.io
        id: push-arm64
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image-arm64.outputs.image }}
          tags: ${{ needs.versioning.outputs.release_tag }}-arm64
          registry: quay.io/kubealex
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          
      - name: Print image url
        run: echo "Images pushed to\n${{ steps.push-x86.outputs.registry-paths }}\n${{ steps.push-arm64.outputs.registry-paths }}"

      
