name: Build and Push Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.1
      id: bump-version
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        default_bump: false     
          
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: my-app
        tags: ${{ steps.bump-version.outputs.new_tag || steps.bump-version.outputs.previous_tag }}
        containerfiles: |
          ./Dockerfile
          ./Dockerfile-test

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.bump-version.outputs.new_tag || steps.bump-version.outputs.previous_tag }}
        registry: quay.io/kubealex
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

      
